# Generated by Django 3.2.5 on 2021-08-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
