# Generated by Django 3.2.5 on 2021-08-15 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
